### ISSUE TITLE
how to keep the view scrolled when clicks an image in the shipped region

### ISSUE THREAD

**Issue by romancanoniero** [Tunous/SwipeActionView#21]
HI! im using the library and I have the problem that when I click in a image contained in the scrolled view , the main layout returns to the original position when I want to keep it open... do you know how to do it?

thanks! Roman

**Comment by Tunous** [comment]
Can you share a small sample code snippet which reproduces this issue?

**Comment by biniamHaddish** [comment]
Try to use this library for that https://github.com/biniamHaddish/SwipeView
