### ISSUE TITLE
Expose drag resistance from initial position outside view

### ISSUE THREAD

**Issue by teal77** [Tunous/SwipeActionView#25]
Hey thanks for the library.

I have a usecase where swipe action is non destructive. ie It results in an archival rather than deletion. 

Having the resistance to drag is not really necessary for me and I would like to configure the view in such a way that it skips the resistance calculation. [(here?)](https://github.com/Tunous/SwipeActionView/blob/03c14d6658c86d628fa6213f495abbf0639abe70/library/src/main/kotlin/me/thanel/swipeactionview/SwipeActionView.kt#L746-L750)

Can you please provide an API for this? Thanks.

**Comment by Tunous** [comment]
Yes, that looks to be the correct place. Would you be willing to make a pull request for that? Ideally we could allow library users to choose resistance of their preference.

**Comment by teal77** [comment]
Sure. Do you have a preferred name for the property? Is `dragResistance` good enough?

**Comment by Tunous** [comment]
Sounds good.
